const axios = require("axios");
const FitnessProfile = require("../models/FitnessProfile");
const Meal = require("../models/Meal");
const WeightLog = require("../models/WeightLog");
const Reminder = require("../models/Reminder");
const WorkoutLog = require("../models/WorkoutLog");
const FitnessDailyLog = require("../models/FitnessDailyLog");
const {
  calculateNutrition,
  calculateHealthTargets,
  estimateWorkoutCalories,
  projectGoal,
  calculateStreak,
  calculateDailyScore,
} = require("../utils/fitnessCalculations");
const { loadAiSettings, getProviderKey, isProviderEnabled } = require("../utils/aiSettingsStore");
const { normalizeNutrition } = require("../utils/fitnessNutrition");
const { sendPushToProfile } = require("../utils/pushNotifications");

const startOfDay = (value = new Date()) => {
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) throw new Error("Invalid date");
  date.setHours(0, 0, 0, 0);
  return date;
};
const endOfDay = (value = new Date()) => new Date(startOfDay(value).getTime() + 86400000);
const owner = (req) => req.profile?._id;
const badRequest = (res, message) => res.status(400).json({ success: false, message });
const handleError = (res, error) => {
  if (error?.name === "ValidationError" || error?.name === "CastError") return badRequest(res, error.message);
  console.error("Fitness request failed:", error);
  return res.status(500).json({ success: false, message: "Fitness request failed" });
};
const isProviderTimeout = (error) => error?.code === "ECONNABORTED" || error?.code === "ETIMEDOUT";
const pick = (source, keys) => keys.reduce((result, key) => {
  if (source[key] !== undefined) result[key] = source[key];
  return result;
}, {});
const dayKey = (value) => {
  const date = startOfDay(value);
  return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;
};
const PROFILE_FIELDS = ["sex", "age", "heightCm", "weightKg", "activityLevel", "goal", "pace", "timezone", "targetWeightKg", "dietaryPreferences", "allergies", "onboardingCompleted"];
const isValidTimezone = (value) => {
  try {
    new Intl.DateTimeFormat("en-US", { timeZone: value }).format();
    return true;
  } catch (_) {
    return false;
  }
};

const buildAutoReminders = (profile) => {
  const calories = Math.round(Number(profile.targetCalories) || 0);
  const goalText = profile.goal === "lose"
    ? "support your weight-loss goal"
    : profile.goal === "gain"
      ? "support your weight-gain goal"
      : "support your maintenance goal";
  const movementTitle = ["very_active", "extra_active"].includes(profile.activityLevel)
    ? "Plan your workout"
    : "Take a movement break";
  return [
    {
      autoKey: "breakfast",
      title: "Breakfast reminder",
      type: "meal",
      time: "08:00",
      timezone: profile.timezone,
      message: `Log a balanced breakfast to ${goalText}${calories ? ` within your ${calories} kcal daily target` : ""}.`,
    },
    {
      autoKey: "lunch",
      title: "Lunch reminder",
      type: "meal",
      time: "13:00",
      timezone: profile.timezone,
      message: `Choose a protein- and vegetable-rich lunch to ${goalText}.`,
    },
    {
      autoKey: "dinner",
      title: "Dinner reminder",
      type: "meal",
      time: "20:00",
      timezone: profile.timezone,
      message: "Log dinner and keep the portion aligned with your remaining daily targets.",
    },
    {
      autoKey: "water-morning",
      title: "Drink water",
      type: "water",
      time: "10:00",
      timezone: profile.timezone,
      message: "Drink water and check in with your energy before your next meal.",
    },
    {
      autoKey: "water-afternoon",
      title: "Drink water",
      type: "water",
      time: "15:00",
      timezone: profile.timezone,
      message: "Drink water to stay hydrated through the afternoon.",
    },
    {
      autoKey: "movement",
      title: movementTitle,
      type: "workout",
      time: "18:00",
      timezone: profile.timezone,
      message: profile.activityLevel === "sedentary"
        ? "Try a short, comfortable walk or stretch. Adjust for your health needs."
        : "Keep your planned activity consistent with your fitness goal.",
    },
  ];
};

const ensureAutoReminders = async (userId, profile) => {
  const reminders = buildAutoReminders(profile);
  await Promise.all(reminders.map((reminder) => Reminder.findOneAndUpdate(
    { user: userId, autoKey: reminder.autoKey },
    { ...reminder, user: userId, autoGenerated: true, enabled: true },
    { upsert: true, new: true, runValidators: true, setDefaultsOnInsert: true },
  )));
};

const getDailyBurn = async (userId, date) => {
  const totals = await WorkoutLog.aggregate([
    { $match: { user: userId, date: { $gte: startOfDay(date), $lt: endOfDay(date) } } },
    { $group: { _id: null, caloriesBurned: { $sum: "$caloriesBurned" }, durationMin: { $sum: "$durationMin" }, workouts: { $sum: 1 } } },
  ]);
  return totals[0] || { caloriesBurned: 0, durationMin: 0, workouts: 0 };
};

const derivedProfileFields = (profile) => {
  const nutrition = calculateNutrition(profile);
  const health = calculateHealthTargets(profile);
  return {
    bmr: nutrition.bmr,
    tdee: nutrition.tdee,
    targetCalories: nutrition.targetCalories,
    macros: nutrition.macros,
    bmi: health.bmi,
    waterTargetMl: health.waterTargetMl,
    stepTarget: health.stepTarget,
    weeklyWorkoutTarget: health.weeklyWorkoutTarget,
    sleepTargetHours: health.sleepTargetHours,
  };
};

// Older profiles were saved before habit targets existed.
const withTargets = (profile) => {
  if (!profile) return profile;
  const health = calculateHealthTargets(profile);
  return {
    ...profile,
    bmi: profile.bmi ?? health.bmi,
    bmiCategory: health.bmiCategory,
    healthyWeightRangeKg: health.healthyWeightRangeKg,
    waterTargetMl: profile.waterTargetMl || health.waterTargetMl,
    stepTarget: profile.stepTarget || health.stepTarget,
    weeklyWorkoutTarget: profile.weeklyWorkoutTarget || health.weeklyWorkoutTarget,
    sleepTargetHours: profile.sleepTargetHours || health.sleepTargetHours,
    pace: profile.pace || "standard",
  };
};

const getDailyTotals = async (userId, date) => {
  const totals = await Meal.aggregate([
    { $match: { user: userId, date: { $gte: startOfDay(date), $lt: endOfDay(date) } } },
    { $group: { _id: null, calories: { $sum: "$calories" }, proteinG: { $sum: "$proteinG" }, carbsG: { $sum: "$carbsG" }, fatG: { $sum: "$fatG" }, fiberG: { $sum: "$fiberG" } } },
  ]);
  return totals[0] || { calories: 0, proteinG: 0, carbsG: 0, fatG: 0, fiberG: 0 };
};

const notifyHealthTargets = async (userId, date, totals) => {
  const profile = await FitnessProfile.findOne({ user: userId });
  if (!profile) return;

  const dayKey = startOfDay(date).toISOString().slice(0, 10);
  const previous = profile.targetNotifications?.date === dayKey
    ? profile.targetNotifications
    : { date: dayKey, calories: false, protein: false, weight: false };
  const notifications = [];
  if (!previous.calories && profile.targetCalories > 0 && totals.calories >= profile.targetCalories) {
    notifications.push({
      key: "calories",
      title: "Daily calorie target reached",
      body: `You reached your ${Math.round(profile.targetCalories)} kcal target today. Keep your next choices balanced.`,
    });
  }
  if (!previous.protein && profile.macros?.proteinG > 0 && totals.proteinG >= profile.macros.proteinG) {
    notifications.push({
      key: "protein",
      title: "Protein target reached",
      body: `You reached your ${Math.round(profile.macros.proteinG)} g protein target today. Great work.`,
    });
  }
  if (!notifications.length) return;

  const claimed = { ...previous };
  notifications.forEach(({ key }) => { claimed[key] = true; });
  await FitnessProfile.updateOne({ _id: profile._id }, { $set: { targetNotifications: claimed } });
  for (const notification of notifications) {
    try {
      await sendPushToProfile(userId, {
        title: notification.title,
        body: notification.body,
        data: { type: "fitness_target", target: notification.key, date: dayKey },
      });
    } catch (error) {
      console.error("[fitness-target] push failed:", error?.message || error);
    }
  }
};

const notifyWeightTarget = async (userId, weightKg) => {
  const profile = await FitnessProfile.findOne({ user: userId });
  if (!profile?.targetWeightKg || profile.targetNotifications?.weight) return;
  const reached = profile.goal === "gain"
    ? weightKg >= profile.targetWeightKg
    : profile.goal === "lose"
      ? weightKg <= profile.targetWeightKg
      : false;
  if (!reached) return;
  await FitnessProfile.updateOne({ _id: profile._id }, { $set: { "targetNotifications.weight": true } });
  try {
    await sendPushToProfile(userId, {
      title: "Weight target reached",
      body: `You reached your ${profile.targetWeightKg} kg goal. Celebrate your progress and maintain healthy habits.`,
      data: { type: "fitness_target", target: "weight" },
    });
  } catch (error) {
    console.error("[fitness-target] weight push failed:", error?.message || error);
  }
};

const notifyAiFitnessUpdate = async (userId, title, body, target) => {
  try {
    await sendPushToProfile(userId, {
      title,
      body,
      data: { type: "fitness_ai_update", target },
    });
  } catch (error) {
    console.error("[fitness-ai] push failed:", error?.message || error);
  }
};

const getProfile = async (req, res) => {
  try {
    const profile = await FitnessProfile.findOne({ user: owner(req) }).lean();
    return res.json({ success: true, profile: withTargets(profile) });
  } catch (error) { return handleError(res, error); }
};

const saveProfile = async (req, res) => {
  try {
    const payload = { ...pick(req.body, PROFILE_FIELDS), onboardingCompleted: req.body.onboardingCompleted !== false };
    if (payload.timezone !== undefined && !isValidTimezone(payload.timezone)) {
      return badRequest(res, "Invalid timezone");
    }
    if (payload.targetWeightKg === "" || payload.targetWeightKg === null) delete payload.targetWeightKg;
    ["age", "heightCm", "weightKg", "targetWeightKg"].forEach((key) => {
      if (payload[key] !== undefined) payload[key] = Number(payload[key]);
    });
    let derived;
    try {
      derived = derivedProfileFields(payload);
    } catch (error) {
      return badRequest(res, error.message);
    }
    const existing = await FitnessProfile.findOne({ user: owner(req) }).lean();
    // Goal progress is measured from the weight at which the current goal was set.
    const goalChanged = !existing?.startWeightKg || existing.goal !== payload.goal || existing.targetWeightKg !== payload.targetWeightKg;
    const startWeightKg = goalChanged ? payload.weightKg : existing.startWeightKg;
    const unset = payload.targetWeightKg === undefined ? { $unset: { targetWeightKg: 1 } } : {};
    const profile = await FitnessProfile.findOneAndUpdate(
      { user: owner(req) },
      { $set: { ...payload, user: owner(req), ...derived, startWeightKg }, ...unset },
      { new: true, upsert: true, runValidators: true, setDefaultsOnInsert: true },
    );
    try {
      await ensureAutoReminders(owner(req), profile);
    } catch (error) {
      console.error("[fitness-reminder] automatic reminder setup failed:", error?.message || error);
    }
    return res.json({ success: true, profile: withTargets(profile.toObject()) });
  } catch (error) { return handleError(res, error); }
};

const resetFitness = async (req, res) => {
  try {
    const user = owner(req);
    await Promise.all([
      FitnessProfile.deleteOne({ user }),
      Meal.deleteMany({ user }),
      WeightLog.deleteMany({ user }),
      Reminder.deleteMany({ user }),
      WorkoutLog.deleteMany({ user }),
      FitnessDailyLog.deleteMany({ user }),
    ]);
    return res.json({ success: true, message: "Fitness details were reset" });
  } catch (error) { return handleError(res, error); }
};

const dashboard = async (req, res) => {
  try {
    const user = owner(req);
    const date = req.query.date || new Date();
    const dayStart = startOfDay(date);
    const weekStart = new Date(dayStart.getTime() - 6 * 86400000);
    const streakStart = new Date(dayStart.getTime() - 120 * 86400000);
    const [rawProfile, meals, totals, burn, latestWeight, reminders, daily, workouts, weekMeals, weekWorkouts, mealDays, workoutDays, habitDays] = await Promise.all([
      FitnessProfile.findOne({ user }).lean(),
      Meal.find({ user, date: { $gte: dayStart, $lt: endOfDay(date) } }).sort({ date: 1, createdAt: 1 }).lean(),
      getDailyTotals(user, date),
      getDailyBurn(user, date),
      WeightLog.findOne({ user }).sort({ date: -1 }).lean(),
      Reminder.find({ user, enabled: true }).sort({ time: 1 }).lean(),
      FitnessDailyLog.findOne({ user, date: dayStart }).lean(),
      WorkoutLog.find({ user, date: { $gte: dayStart, $lt: endOfDay(date) } }).sort({ date: -1 }).lean(),
      Meal.find({ user, date: { $gte: weekStart, $lt: endOfDay(date) } }).select("date calories").lean(),
      WorkoutLog.find({ user, date: { $gte: weekStart, $lt: endOfDay(date) } }).select("date durationMin caloriesBurned").lean(),
      Meal.find({ user, date: { $gte: streakStart } }).select("date").lean(),
      WorkoutLog.find({ user, date: { $gte: streakStart } }).select("date").lean(),
      FitnessDailyLog.find({ user, date: { $gte: streakStart }, $or: [{ waterMl: { $gt: 0 } }, { steps: { $gt: 0 } }] }).select("date").lean(),
    ]);
    const profile = withTargets(rawProfile);
    if (!profile) return res.json({ success: true, date: dayStart, profile: null });

    const week = Array.from({ length: 7 }, (_, index) => {
      const key = dayKey(new Date(weekStart.getTime() + index * 86400000));
      return { date: key, calories: 0, caloriesBurned: 0, activeMinutes: 0, workouts: 0 };
    });
    const weekByKey = Object.fromEntries(week.map((item) => [item.date, item]));
    weekMeals.forEach((meal) => { const bucket = weekByKey[dayKey(meal.date)]; if (bucket) bucket.calories += meal.calories || 0; });
    weekWorkouts.forEach((workout) => {
      const bucket = weekByKey[dayKey(workout.date)];
      if (!bucket) return;
      bucket.caloriesBurned += workout.caloriesBurned || 0;
      bucket.activeMinutes += workout.durationMin || 0;
      bucket.workouts += 1;
    });
    week.forEach((item) => { item.calories = Math.round(item.calories); });

    const todayKey = dayKey(date);
    const streak = calculateStreak([...mealDays, ...workoutDays, ...habitDays].map((item) => dayKey(item.date)), todayKey);
    const currentWeightKg = latestWeight?.weightKg || profile.weightKg;
    const goalProgress = projectGoal({
      startWeightKg: profile.startWeightKg || profile.weightKg,
      currentWeightKg,
      targetWeightKg: profile.targetWeightKg,
      goal: profile.goal,
      pace: profile.pace,
    });
    const habits = { waterMl: daily?.waterMl || 0, steps: daily?.steps || 0, sleepHours: daily?.sleepHours || 0, mood: daily?.mood || null };
    const score = calculateDailyScore({
      calories: totals.calories,
      targetCalories: profile.targetCalories,
      proteinG: totals.proteinG,
      proteinTarget: profile.macros?.proteinG,
      waterMl: habits.waterMl,
      waterTarget: profile.waterTargetMl,
      steps: habits.steps,
      stepTarget: profile.stepTarget,
      activeMinutes: burn.durationMin,
      sleepHours: habits.sleepHours,
      sleepTarget: profile.sleepTargetHours,
    });
    return res.json({
      success: true,
      date: dayStart,
      profile,
      meals,
      mealCount: meals.length,
      totals,
      burn,
      habits,
      workouts,
      week,
      weekSummary: {
        workouts: week.reduce((sum, item) => sum + item.workouts, 0),
        activeMinutes: week.reduce((sum, item) => sum + item.activeMinutes, 0),
        workoutTarget: profile.weeklyWorkoutTarget,
      },
      streak,
      currentWeightKg,
      goalProgress,
      score,
      latestWeight,
      reminders,
    });
  } catch (error) { return handleError(res, error); }
};

const listMeals = async (req, res) => {
  try {
    const date = req.query.date || new Date();
    const meals = await Meal.find({ user: owner(req), date: { $gte: startOfDay(date), $lt: endOfDay(date) } }).sort({ createdAt: -1 }).lean();
    return res.json({ success: true, meals, totals: await getDailyTotals(owner(req), date) });
  } catch (error) { return handleError(res, error); }
};

// Distinct meals from the last 30 days so users can re-log favourites in one tap.
const recentMeals = async (req, res) => {
  try {
    const meals = await Meal.aggregate([
      { $match: { user: owner(req), date: { $gte: new Date(Date.now() - 30 * 86400000) } } },
      { $sort: { date: -1 } },
      {
        $group: {
          _id: { $toLower: "$name" },
          name: { $first: "$name" },
          mealType: { $first: "$mealType" },
          calories: { $first: "$calories" },
          proteinG: { $first: "$proteinG" },
          carbsG: { $first: "$carbsG" },
          fatG: { $first: "$fatG" },
          fiberG: { $first: "$fiberG" },
          count: { $sum: 1 },
          lastLogged: { $first: "$date" },
        },
      },
      { $sort: { count: -1, lastLogged: -1 } },
      { $limit: 10 },
    ]);
    return res.json({ success: true, meals: meals.map(({ _id, ...meal }) => meal) });
  } catch (error) { return handleError(res, error); }
};

const createMeal = async (req, res) => {
  try {
    const { date, mealType, name, servings, calories, proteinG, carbsG, fatG, fiberG, notes, source, imageUrl, analysis, foods } = req.body;
    if (!name || !String(name).trim()) return badRequest(res, "Meal name is required");
    const mealDate = new Date(date || Date.now());
    if (Number.isNaN(mealDate.getTime())) return badRequest(res, "A valid meal date is required");
    const meal = await Meal.create({ user: owner(req), date: mealDate, mealType, name, servings, calories, proteinG, carbsG, fatG, fiberG, notes, source, imageUrl, analysis, foods, userConfirmedAt: new Date() });
    const totals = await getDailyTotals(owner(req), meal.date);
    try {
      await notifyHealthTargets(owner(req), meal.date, totals);
    } catch (error) {
      console.error("[fitness-target] meal milestone check failed:", error?.message || error);
    }
    return res.status(201).json({ success: true, meal, totals });
  } catch (error) { return handleError(res, error); }
};

const getMeal = async (req, res) => {
  try {
    const meal = await Meal.findOne({ _id: req.params.id, user: owner(req) }).lean();
    if (!meal) return res.status(404).json({ success: false, message: "Meal not found" });
    return res.json({ success: true, meal });
  } catch (error) {
    return handleError(res, error);
  }
};

const updateMeal = async (req, res) => {
  try {
    const update = pick(req.body, ["date", "mealType", "name", "servings", "calories", "proteinG", "carbsG", "fatG", "fiberG", "notes", "source", "imageUrl", "analysis", "foods"]);
    update.userConfirmedAt = new Date();
    if (update.date) {
      update.date = new Date(update.date);
      if (Number.isNaN(update.date.getTime())) return badRequest(res, "A valid meal date is required");
    }
    const meal = await Meal.findOneAndUpdate({ _id: req.params.id, user: owner(req) }, update, { new: true, runValidators: true });
    if (!meal) return res.status(404).json({ success: false, message: "Meal not found" });
    return res.json({ success: true, meal });
  } catch (error) { return handleError(res, error); }
};

const deleteMeal = async (req, res) => {
  try {
    const meal = await Meal.findOneAndDelete({ _id: req.params.id, user: owner(req) });
    if (!meal) return res.status(404).json({ success: false, message: "Meal not found" });
    return res.json({ success: true, totals: await getDailyTotals(owner(req), meal.date) });
  } catch (error) { return handleError(res, error); }
};

const analyzeMeal = async (req, res) => {
  const name = String(req.body?.name || req.body?.description || "").trim();
  const mealType = ["breakfast", "lunch", "dinner", "snack"].includes(req.body?.mealType) ? req.body.mealType : "snack";
  if (name.length > 500) return badRequest(res, "A food description up to 500 characters is required");
  if (!name && !req.file) return badRequest(res, "Add a food name or photo to analyze");
  try {
    const enabled = await isProviderEnabled("gemini");
    const settings = await loadAiSettings();
    const key = await getProviderKey("gemini");
    if (!enabled || !key) {
      return res.json({ success: true, provider: "placeholder", requiresConfirmation: true, analysis: { name: name || "Analyzed meal", serving: "1 serving", calories: null, proteinG: null, carbsG: null, fatG: null, fiberG: null } });
    }
    const prompt = `Analyze this ${mealType} food image${name ? ` or description: ${name}` : ""} for one serving. Identify the food name from the image when possible. Return ONLY JSON with name, serving, calories, proteinG, carbsG, fatG, fiberG. Use conservative numeric estimates; never use null.`;
    const model = settings.models?.gemini || "gemini-2.0-flash";
    const response = await axios.post(
      `https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(key)}`,
      {
        contents: [{
          role: "user",
          parts: [
            { text: prompt },
            ...(req.file ? [{ inlineData: { mimeType: req.file.mimetype, data: req.file.buffer.toString("base64") } }] : []),
          ],
        }],
        generationConfig: { temperature: 0, responseMimeType: "application/json" },
      },
      { timeout: 20000, validateStatus: () => true },
    );
    if (response.status >= 400) return res.status(502).json({ success: false, message: "Food analysis is temporarily unavailable" });
    const text = response.data?.candidates?.[0]?.content?.parts?.map((part) => part.text || "").join("") || "{}";
    let analysis;
    try {
      analysis = normalizeNutrition(JSON.parse(text.replace(/^```json\s*|\s*```$/gi, "").trim()), name || "Analyzed meal");
    } catch (error) {
      return res.status(502).json({ success: false, message: "Food analysis returned invalid nutrition data" });
    }
    await notifyAiFitnessUpdate(
      owner(req),
      "Food analysis ready",
      "Your AI nutrition estimate is ready to review and save.",
      "food_analysis",
    );
    return res.json({ success: true, provider: "gemini", requiresConfirmation: true, analysis });
  } catch (error) {
    if (isProviderTimeout(error)) {
      console.warn("Gemini food analysis timed out");
      return res.status(504).json({ success: false, message: "Food analysis timed out. You can add this meal manually." });
    }
    console.error("Gemini food analysis failed:", error?.code || error?.message || "unknown provider error");
    return res.status(502).json({ success: false, message: "Food analysis is temporarily unavailable. You can add this meal manually." });
  }
};

const listWeights = async (req, res) => {
  try { return res.json({ success: true, weights: await WeightLog.find({ user: owner(req) }).sort({ date: -1 }).limit(365).lean() }); }
  catch (error) { return handleError(res, error); }
};
const addWeight = async (req, res) => {
  try {
    const logDate = startOfDay(req.body.date || new Date());
    const weight = await WeightLog.findOneAndUpdate(
      { user: owner(req), date: logDate },
      { ...pick(req.body, ["weightKg", "bodyFatPercent", "note"]), user: owner(req), date: logDate },
      { new: true, upsert: true, runValidators: true, setDefaultsOnInsert: true },
    );
    try {
      // Keep calorie and hydration targets in step with the newest weigh-in.
      const [profile, latest] = await Promise.all([
        FitnessProfile.findOne({ user: owner(req) }).lean(),
        WeightLog.findOne({ user: owner(req) }).sort({ date: -1 }).lean(),
      ]);
      if (profile && String(latest?._id) === String(weight._id)) {
        await FitnessProfile.updateOne({ _id: profile._id }, { $set: { weightKg: weight.weightKg, ...derivedProfileFields({ ...profile, weightKg: weight.weightKg }) } });
      }
    } catch (error) {
      console.error("[fitness] target refresh after weigh-in failed:", error?.message || error);
    }
    try {
      await notifyWeightTarget(owner(req), weight.weightKg);
    } catch (error) {
      console.error("[fitness-target] weight milestone check failed:", error?.message || error);
    }
    return res.status(201).json({ success: true, weight });
  } catch (error) { return handleError(res, error); }
};
const deleteWeight = async (req, res) => {
  try {
    const weight = await WeightLog.findOneAndDelete({ _id: req.params.id, user: owner(req) });
    if (!weight) return res.status(404).json({ success: false, message: "Weight entry not found" });
    return res.json({ success: true });
  } catch (error) { return handleError(res, error); }
};

const getDaily = async (req, res) => {
  try {
    const date = startOfDay(req.query.date || new Date());
    const daily = await FitnessDailyLog.findOne({ user: owner(req), date }).lean();
    return res.json({ success: true, daily: daily || { date, waterMl: 0, steps: 0, sleepHours: 0 } });
  } catch (error) { return handleError(res, error); }
};

/**
 * Upsert a day's habits. `addWaterMl` increments (negative undoes a glass);
 * `waterMl`, `steps`, `sleepHours` and `mood` set absolute values.
 */
const updateDaily = async (req, res) => {
  try {
    const date = startOfDay(req.body.date || new Date());
    const set = pick(req.body, ["waterMl", "steps", "sleepHours", "mood"]);
    for (const [key, value] of Object.entries(set)) {
      const number = Number(value);
      if (!Number.isFinite(number) || number < 0) return badRequest(res, `${key} must be a positive number`);
      set[key] = number;
    }
    const addWaterMl = Number(req.body.addWaterMl) || 0;
    if (Math.abs(addWaterMl) > 3000) return badRequest(res, "addWaterMl is too large");
    const daily = await FitnessDailyLog.findOneAndUpdate(
      { user: owner(req), date },
      { $set: { ...set, user: owner(req), date } },
      { new: true, upsert: true, runValidators: true, setDefaultsOnInsert: true },
    );
    if (addWaterMl) {
      daily.waterMl = Math.min(10000, Math.max(0, (daily.waterMl || 0) + addWaterMl));
      await daily.save();
    }
    return res.json({ success: true, daily });
  } catch (error) { return handleError(res, error); }
};

const WORKOUT_FIELDS = ["date", "name", "type", "intensity", "durationMin", "caloriesBurned", "exercises", "notes"];

const workoutPayload = async (req, body) => {
  const payload = pick(body, WORKOUT_FIELDS);
  if (payload.date !== undefined) {
    payload.date = new Date(payload.date);
    if (Number.isNaN(payload.date.getTime())) throw Object.assign(new Error("A valid workout date is required"), { name: "ValidationError" });
  }
  if (payload.caloriesBurned === undefined || payload.caloriesBurned === "" || payload.caloriesBurned === null) {
    const profile = await FitnessProfile.findOne({ user: owner(req) }).select("weightKg").lean();
    payload.caloriesBurned = estimateWorkoutCalories({ ...payload, weightKg: profile?.weightKg });
  }
  return payload;
};

const listWorkouts = async (req, res) => {
  try {
    const days = Math.min(365, Math.max(1, Number(req.query.days) || 30));
    const since = startOfDay(new Date(Date.now() - (days - 1) * 86400000));
    const workouts = await WorkoutLog.find({ user: owner(req), date: { $gte: since } }).sort({ date: -1 }).limit(200).lean();
    return res.json({ success: true, workouts });
  } catch (error) { return handleError(res, error); }
};

const createWorkout = async (req, res) => {
  try {
    const payload = await workoutPayload(req, { date: new Date(), ...req.body });
    if (!payload.name || !String(payload.name).trim()) return badRequest(res, "Workout name is required");
    const workout = await WorkoutLog.create({ ...payload, user: owner(req) });
    return res.status(201).json({ success: true, workout, burn: await getDailyBurn(owner(req), workout.date) });
  } catch (error) { return handleError(res, error); }
};

const updateWorkout = async (req, res) => {
  try {
    const payload = await workoutPayload(req, req.body);
    const workout = await WorkoutLog.findOneAndUpdate({ _id: req.params.id, user: owner(req) }, payload, { new: true, runValidators: true });
    if (!workout) return res.status(404).json({ success: false, message: "Workout not found" });
    return res.json({ success: true, workout });
  } catch (error) { return handleError(res, error); }
};

const deleteWorkout = async (req, res) => {
  try {
    const workout = await WorkoutLog.findOneAndDelete({ _id: req.params.id, user: owner(req) });
    if (!workout) return res.status(404).json({ success: false, message: "Workout not found" });
    return res.json({ success: true });
  } catch (error) { return handleError(res, error); }
};

const progress = async (req, res) => {
  try {
    const period = ["daily", "weekly", "monthly", "quarterly"].includes(req.query.period)
      ? req.query.period
      : "monthly";
    const days = { daily: 1, weekly: 7, monthly: 30, quarterly: 90 }[period];
    const since = startOfDay(new Date(Date.now() - (days - 1) * 86400000));
    // Bucket by the server timezone so keys match startOfDay()-based habit and weight days.
    const serverTimezone = Intl.DateTimeFormat().resolvedOptions().timeZone || "UTC";
    const dayKeys = Array.from({ length: days }, (_, index) => dayKey(new Date(since.getTime() + index * 86400000 + 43200000)));
    const [rawProfile, workouts, habits, weights, meals] = await Promise.all([
      FitnessProfile.findOne({ user: owner(req) }).lean(),
      WorkoutLog.aggregate([
        { $match: { user: owner(req), date: { $gte: since } } },
        {
          $group: {
            _id: { $dateToString: { format: "%Y-%m-%d", date: "$date", timezone: serverTimezone } },
            durationMin: { $sum: "$durationMin" },
            caloriesBurned: { $sum: "$caloriesBurned" },
            workouts: { $sum: 1 },
          },
        },
        { $sort: { _id: 1 } },
      ]),
      FitnessDailyLog.find({ user: owner(req), date: { $gte: since } }).sort({ date: 1 }).select("date waterMl steps sleepHours").lean(),
      WeightLog.find({ user: owner(req), date: { $gte: since } }).sort({ date: 1 }).lean(),
      Meal.aggregate([
        { $match: { user: owner(req), date: { $gte: since } } },
        {
          $group: {
            _id: { $dateToString: { format: "%Y-%m-%d", date: "$date", timezone: serverTimezone } },
            calories: { $sum: "$calories" },
            proteinG: { $sum: "$proteinG" },
            carbsG: { $sum: "$carbsG" },
            fatG: { $sum: "$fatG" },
            meals: { $sum: 1 },
          },
        },
        { $sort: { _id: 1 } },
      ]),
    ]);
    const totalCalories = meals.reduce((sum, item) => sum + item.calories, 0);
    const profile = withTargets(rawProfile);
    const target = profile?.targetCalories || 0;
    const onTargetDays = target ? meals.filter((item) => Math.abs(item.calories - target) <= target * 0.1).length : 0;
    const average = (items, key) => {
      const values = items.map((item) => Number(item[key]) || 0).filter((value) => value > 0);
      return values.length ? Math.round((values.reduce((sum, value) => sum + value, 0) / values.length) * 10) / 10 : 0;
    };
    const firstWeight = weights[0]?.weightKg;
    const lastWeight = weights[weights.length - 1]?.weightKg;
    return res.json({
      success: true,
      period,
      days,
      since,
      dayKeys,
      targets: profile ? {
        calories: profile.targetCalories,
        proteinG: profile.macros?.proteinG,
        carbsG: profile.macros?.carbsG,
        fatG: profile.macros?.fatG,
        sleepHours: profile.sleepTargetHours,
        waterMl: profile.waterTargetMl,
        steps: profile.stepTarget,
        targetWeightKg: profile.targetWeightKg,
      } : null,
      weights: weights.map((entry) => ({ ...entry, day: dayKey(entry.date) })),
      nutrition: meals,
      workouts,
      habits: habits.map((entry) => ({ ...entry, day: dayKey(entry.date) })),
      summary: {
        onTargetDays,
        adherencePercent: meals.length ? Math.round((onTargetDays / meals.length) * 100) : 0,
        workoutCount: workouts.reduce((sum, item) => sum + item.workouts, 0),
        activeMinutes: workouts.reduce((sum, item) => sum + item.durationMin, 0),
        caloriesBurned: workouts.reduce((sum, item) => sum + item.caloriesBurned, 0),
        averageSteps: Math.round(average(habits, "steps")),
        averageWaterMl: Math.round(average(habits, "waterMl")),
        averageSleepHours: average(habits, "sleepHours"),
        weightChangeKg: firstWeight && lastWeight ? Math.round((lastWeight - firstWeight) * 10) / 10 : 0,
        loggedDays: meals.length,
        totalCalories,
        averageCalories: meals.length ? Math.round(totalCalories / meals.length) : 0,
        totalProteinG: meals.reduce((sum, item) => sum + item.proteinG, 0),
        totalCarbsG: meals.reduce((sum, item) => sum + item.carbsG, 0),
        totalFatG: meals.reduce((sum, item) => sum + item.fatG, 0),
      },
    });
  } catch (error) { return handleError(res, error); }
};

const coach = async (req, res) => {
  const question = String(req.body?.question || "").trim();
  if (!question || question.length > 500) return badRequest(res, "A question up to 500 characters is required");
  try {
    const [rawProfile, totals, meals, burn, daily, latestWeight] = await Promise.all([
      FitnessProfile.findOne({ user: owner(req) }).lean(),
      getDailyTotals(owner(req), new Date()),
      Meal.find({ user: owner(req), date: { $gte: startOfDay(new Date()), $lt: endOfDay(new Date()) } })
        .sort({ date: -1 })
        .select("name mealType calories proteinG carbsG fatG fiberG date")
        .lean(),
      getDailyBurn(owner(req), new Date()),
      FitnessDailyLog.findOne({ user: owner(req), date: startOfDay(new Date()) }).lean(),
      WeightLog.findOne({ user: owner(req) }).sort({ date: -1 }).lean(),
    ]);
    if (!rawProfile) return badRequest(res, "Complete your fitness profile first");
    const profile = withTargets(rawProfile);
    // Short client-kept conversation so follow-up questions have context.
    const history = (Array.isArray(req.body?.history) ? req.body.history : [])
      .slice(-6)
      .filter((turn) => turn && typeof turn.text === "string" && ["user", "coach"].includes(turn.role))
      .map((turn) => ({ role: turn.role === "coach" ? "model" : "user", parts: [{ text: turn.text.slice(0, 1200) }] }));
    const key = await getProviderKey("gemini");
    if (!(await isProviderEnabled("gemini")) || !key) {
      return res.json({ success: true, reply: "Your fitness profile is ready. Add meals to get personalized guidance within your remaining calories." });
    }
    const settings = await loadAiSettings();
    const context = JSON.stringify({
      goal: profile.goal,
      pace: profile.pace,
      age: profile.age,
      sex: profile.sex,
      activityLevel: profile.activityLevel,
      currentWeightKg: latestWeight?.weightKg || profile.weightKg,
      targetWeightKg: profile.targetWeightKg,
      bmi: profile.bmi,
      targetCalories: profile.targetCalories,
      macros: profile.macros,
      dailyTargets: { waterMl: profile.waterTargetMl, steps: profile.stepTarget, sleepHours: profile.sleepTargetHours, weeklyWorkouts: profile.weeklyWorkoutTarget },
      today: totals,
      todayExercise: burn,
      todayHabits: { waterMl: daily?.waterMl || 0, steps: daily?.steps || 0, sleepHours: daily?.sleepHours || 0 },
      meals: meals.map((meal) => ({
        name: meal.name,
        mealType: meal.mealType,
        calories: meal.calories,
        proteinG: meal.proteinG,
        carbsG: meal.carbsG,
        fatG: meal.fatG,
        fiberG: meal.fiberG,
        date: meal.date,
      })),
    });
    const response = await axios.post(
      `https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(settings.models?.gemini || "gemini-2.0-flash")}:generateContent?key=${encodeURIComponent(key)}`,
      {
        systemInstruction: { parts: [{ text: "You are a supportive, evidence-based health and fitness coach covering nutrition, training, hydration, sleep and habits. Use only the supplied numbers for the user's data. Give specific, actionable steps in short paragraphs or bullet points (under 180 words). Do not diagnose, prescribe medication, or recommend dangerous restriction or overtraining. Encourage a clinician for medical questions, pain, or injuries." }] },
        contents: [...history, { role: "user", parts: [{ text: `Context: ${context}\nQuestion: ${question}` }] }],
        generationConfig: { temperature: 0.3, maxOutputTokens: 500 },
      },
      { timeout: 20000, validateStatus: () => true },
    );
    if (response.status >= 400) return res.status(502).json({ success: false, message: "Coach is temporarily unavailable" });
    const reply = response.data?.candidates?.[0]?.content?.parts?.map((part) => part.text || "").join("").trim();
    if (!reply) return res.status(502).json({ success: false, message: "Coach returned no guidance" });
    return res.json({ success: true, reply });
  } catch (error) {
    if (isProviderTimeout(error)) {
      console.warn("Gemini fitness coach timed out");
      return res.status(504).json({ success: false, message: "Coach timed out. Please try again shortly." });
    }
    console.error("Gemini fitness coach failed:", error?.code || error?.message || "unknown provider error");
    return res.status(502).json({ success: false, message: "Coach is temporarily unavailable. Please try again shortly." });
  }
};

const recommendations = async (req, res) => {
  try {
    const refreshToken = String(req.query.refresh || `${Date.now()}-${Math.random()}`);
    const themes = [
      "Try fresh seasonal ingredients and a cuisine you have not logged today.",
      "Prefer quick meals that can be prepared in under 20 minutes.",
      "Prefer budget-friendly common South Asian ingredients.",
      "Prefer high-protein meals with plenty of vegetables.",
      "Prefer light, refreshing meals suitable for a warm day.",
    ];
    const themeIndex = [...refreshToken].reduce((sum, character) => sum + character.charCodeAt(0), 0) % themes.length;
    const varietyInstruction = themes[themeIndex];
    const [profile, totals, meals] = await Promise.all([
      FitnessProfile.findOne({ user: owner(req) }).lean(),
      getDailyTotals(owner(req), new Date()),
      Meal.find({ user: owner(req), date: { $gte: startOfDay(new Date()), $lt: endOfDay(new Date()) } })
        .sort({ date: -1 })
        .select("name mealType calories proteinG carbsG fatG fiberG date")
        .lean(),
    ]);
    if (!profile) return badRequest(res, "Complete your fitness profile first");

    const remaining = {
      calories: Math.max(0, Math.round(profile.targetCalories - totals.calories)),
      proteinG: Math.max(0, Math.round(profile.macros.proteinG - totals.proteinG)),
      carbsG: Math.max(0, Math.round(profile.macros.carbsG - totals.carbsG)),
      fatG: Math.max(0, Math.round(profile.macros.fatG - totals.fatG)),
    };
    const fallbackSets = [
      [
        { name: "Dal, rice and vegetables", mealType: "lunch", calories: 520, proteinG: 20, carbsG: 82, fatG: 11, why: "Balanced local meal with fiber and plant protein." },
        { name: "Grilled fish with salad", mealType: "dinner", calories: 380, proteinG: 34, carbsG: 18, fatG: 18, why: "Protein-rich option with vegetables and healthy fats." },
        { name: "Egg and roti plate", mealType: "breakfast", calories: 410, proteinG: 21, carbsG: 48, fatG: 15, why: "Practical meal with protein and steady carbohydrates." },
      ],
      [
        { name: "Chicken chickpea salad bowl", mealType: "lunch", calories: 460, proteinG: 38, carbsG: 42, fatG: 14, why: "A varied, filling option with lean protein and fiber." },
        { name: "Vegetable omelette with toast", mealType: "breakfast", calories: 330, proteinG: 24, carbsG: 28, fatG: 15, why: "Quick protein-rich meal with vegetables." },
        { name: "Yogurt, fruit and nuts", mealType: "snack", calories: 290, proteinG: 18, carbsG: 32, fatG: 10, why: "Light snack with protein and satisfying healthy fats." },
      ],
      [
        { name: "Beef or tofu stir-fry", mealType: "dinner", calories: 490, proteinG: 32, carbsG: 40, fatG: 19, why: "Flexible protein-forward meal with colorful vegetables." },
        { name: "Tuna cucumber wrap", mealType: "lunch", calories: 370, proteinG: 29, carbsG: 36, fatG: 12, why: "Convenient balanced meal with fresh ingredients." },
        { name: "Banana peanut overnight oats", mealType: "breakfast", calories: 390, proteinG: 16, carbsG: 55, fatG: 13, why: "Fiber-rich breakfast for steady energy." },
      ],
    ];
    const fallback = {
      recommendations: fallbackSets[themeIndex % fallbackSets.length],
      healthNotes: ["Choose mostly whole foods and include vegetables or fruit with meals.", "Drink water regularly and adjust portions to your hunger and activity.", "These are general wellness suggestions, not medical advice."],
    };
    const key = await getProviderKey("gemini");
    if (!(await isProviderEnabled("gemini")) || !key) {
      return res.json({ success: true, source: "curated", totals, remaining, ...fallback });
    }
    const settings = await loadAiSettings();
    const response = await axios.post(
      `https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(settings.models?.gemini || "gemini-2.0-flash")}:generateContent?key=${encodeURIComponent(key)}`,
      {
        systemInstruction: { parts: [{ text: "You are a safe nutrition coach. Never diagnose or prescribe. Use only supplied targets. Return JSON only. Recommend common South Asian foods when appropriate." }] },
        contents: [{ role: "user", parts: [{ text: `Create 3 genuinely different meal recommendations for this refresh request (${refreshToken}). Variety direction: ${varietyInstruction} Do not reuse these meals: ${JSON.stringify(meals.map((meal) => meal.name))}. Context: ${JSON.stringify({ goal: profile.goal, remaining, totals, meals: meals.map((meal) => ({ name: meal.name, mealType: meal.mealType, calories: meal.calories, proteinG: meal.proteinG, carbsG: meal.carbsG, fatG: meal.fatG, fiberG: meal.fiberG, date: meal.date })) })}. Each recommendation must be a realistic single serving, should not exceed the remaining calories by more than 10%, and should prioritize the remaining macro targets. Use different meal types and ingredients where possible. JSON shape: {"recommendations":[{"name":"string","mealType":"breakfast|lunch|dinner|snack","calories":number,"proteinG":number,"carbsG":number,"fatG":number,"why":"string"}],"healthNotes":["string"]}. Keep values plausible and include a disclaimer in healthNotes.` }] }],
        generationConfig: { temperature: 0.85, topP: 0.95, responseMimeType: "application/json", maxOutputTokens: 700 },
      },
      { timeout: 20000, validateStatus: () => true },
    );
    if (response.status >= 400) return res.json({ success: true, source: "curated", totals, remaining, ...fallback });
    const text = response.data?.candidates?.[0]?.content?.parts?.map((part) => part.text || "").join("").trim() || "";
    let result;
    try { result = JSON.parse(text.replace(/^```json\s*|\s*```$/gi, "").trim()); } catch (_) { result = null; }
    if (!result || !Array.isArray(result.recommendations) || result.recommendations.length === 0) {
      return res.json({ success: true, source: "curated", totals, remaining, ...fallback });
    }
    const safeRecommendations = result.recommendations.slice(0, 5).map((item) => ({
      name: String(item.name || "Suggested meal").slice(0, 120),
      calories: Math.max(0, Math.min(2000, Math.round(Number(item.calories) || 0))),
      proteinG: Math.max(0, Math.min(200, Math.round(Number(item.proteinG) || 0))),
      carbsG: Math.max(0, Math.min(300, Math.round(Number(item.carbsG) || 0))),
      fatG: Math.max(0, Math.min(150, Math.round(Number(item.fatG) || 0))),
      mealType: ["breakfast", "lunch", "dinner", "snack"].includes(item.mealType) ? item.mealType : "snack",
      why: String(item.why || "A balanced option within your remaining targets.").slice(0, 300),
    }));
    await notifyAiFitnessUpdate(
      owner(req),
      "Fitness recommendations ready",
      "Your personalized meal recommendations are ready to view.",
      "recommendations",
    );
    return res.json({ success: true, source: "gemini", totals, remaining, recommendations: safeRecommendations, healthNotes: Array.isArray(result.healthNotes) ? result.healthNotes.slice(0, 5).map((note) => String(note).slice(0, 300)) : fallback.healthNotes });
  } catch (error) {
    if (isProviderTimeout(error)) return res.status(504).json({ success: false, message: "Recommendations timed out. Please try again shortly." });
    console.error("Fitness recommendations failed:", error?.code || error?.message || "unknown provider error");
    return res.status(502).json({ success: false, message: "Recommendations are temporarily unavailable" });
  }
};

const listReminders = async (req, res) => {
  try { return res.json({ success: true, reminders: await Reminder.find({ user: owner(req) }).sort({ time: 1 }).lean() }); }
  catch (error) { return handleError(res, error); }
};
const createReminder = async (req, res) => {
  try {
    if (req.body.timezone !== undefined && !isValidTimezone(req.body.timezone)) {
      return badRequest(res, "Invalid timezone");
    }
    const reminder = await Reminder.create({
      ...pick(req.body, ["title", "type", "time", "days", "enabled", "message", "notificationId", "timezone"]),
      user: owner(req),
      autoGenerated: false,
    });
    return res.status(201).json({ success: true, reminder });
  }
  catch (error) { return handleError(res, error); }
};
const updateReminder = async (req, res) => {
  try {
    const update = pick(req.body, ["title", "type", "time", "days", "enabled", "message", "notificationId", "timezone"]);
    if (update.timezone !== undefined && !isValidTimezone(update.timezone)) {
      return badRequest(res, "Invalid timezone");
    }
    const reminder = await Reminder.findOneAndUpdate({ _id: req.params.id, user: owner(req) }, update, { new: true, runValidators: true });
    if (!reminder) return res.status(404).json({ success: false, message: "Reminder not found" });
    return res.json({ success: true, reminder });
  } catch (error) { return handleError(res, error); }
};
const deleteReminder = async (req, res) => {
  try {
    const reminder = await Reminder.findOneAndDelete({ _id: req.params.id, user: owner(req) });
    if (!reminder) return res.status(404).json({ success: false, message: "Reminder not found" });
    return res.json({ success: true });
  } catch (error) { return handleError(res, error); }
};

module.exports = {
  resetFitness, getProfile, saveProfile, dashboard, coach, recommendations,
  listMeals, recentMeals, createMeal, getMeal, updateMeal, deleteMeal, analyzeMeal,
  listWeights, addWeight, deleteWeight, progress,
  getDaily, updateDaily, listWorkouts, createWorkout, updateWorkout, deleteWorkout,
  listReminders, createReminder, updateReminder, deleteReminder,
};
